---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: seed-ingressroutes-tcp
spec:
  entryPoints:
    - p2p
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: p2p-osmosis-seed-0
      port: 26656
      tls: false
